name: Android Build and APK Generation

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["prod"]

jobs:
  build_with_Apk:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Display event information
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Display server information
        run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - run: echo "The workflow is now ready to test your code."

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - run: echo "Building Debug APK."

      - name: Build with Gradle
        run: ./gradlew build

      - run: echo "Build status report=${{ job.status }}."
